package com.gps.shared_resources;

public enum RequestsType {
    LOGIN,
    REGISTER,
    EDIT, DISCONNECT, ADD_SERVICE, EDIT_SERVICE, REMOVE_SERVICE, UPDATE_SERVICES,
    UPDATE_CALENDAR, GET_WORKERS, UPDATE_WEEK, UPDATE_USER_WEEK, GET_TYPE_OF_SERVICE,
    UPDATE_CALENDAR_WORKER, UPDATE_CALENDAR_ASSINC, UPDATE_WEEK_WORKER, LOGIN_WORKER, CONCLUDE_SERVICE
}
